name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: './'
          extensions: 'h,c'
          clangFormatVersion: 10
